version: v2.0
modules:
    - name: backbone
      services:
        - zookeeper-v2
        - elasticsearch-data-v1
        - elasticsearch-master-v1
        - kibana-v1
    - name: authn-authz
      services:
        - redis
        - nginx-ingress
        - cert-manager      
    - name: core
      dependencies:
        - "backbone"
        - "authn-authz"    
      services:
        - ecr/service1:v1.1.0-f9375a4
        - ecr/service2-masters:408-14b79e9
        - ecr/service3:7-uploader-demand-feature-44b0170