global:
  domain: cicd.techminds.dev
cluster-configs:
  namespaces:
    create: true
    values: [ monitoring, jenkins ]
  root-ingress:
    namespace: jenkins
    serviceName: jenkins
    servicePort: 8080
    appRoot: ""
    cert-issuer: "letsencrypt-prod"

jenkins:
  persistence:
    enabled: true
    size: "20Gi"
    aws:
      - volumeId: "vol-01a9fc5693cddbf39"
        zone: ap-south-1b
  oauth:
    enabled: true
    acl:
      admin:
        - kaleyra*core-devops
      user:
        - kaleyra*core-dev
        - kaleyra*core-stage
        - kaleyra*core-preprod
        - kaleyra*core-prod
        - kaleyra*sms-dev
        - kaleyra*sms-stage
        - kaleyra*sms-preprod
        - kaleyra*sms-prod        
        - kaleyra*cap-dev
        - kaleyra*cap-stage
        - kaleyra*cap-preprod
        - kaleyra*voice-dev
        - kaleyra*voice-stage
        - kaleyra*voice-preprod
        - kaleyra*whatsapp-dev
        - kaleyra*whatsapp-stage
        - kaleyra*whatsapp-preprod
        - kaleyra*campaign-dev
        - kaleyra*campaign-stage
        - kaleyra*campaign-preprod
        - kaleyra*PROD

  jobBuilder:
    repos: >-
      'git@bitbucket.org:kaleyra/core.git','git@bitbucket.org:kaleyra/campaign-management.git','git@bitbucket.org:kaleyra/cap.git','git@bitbucket.org:kaleyra/conversational-ai.git','git@bitbucket.org:kaleyra/email.git','git@bitbucket.org:kaleyra/sms.git','git@bitbucket.org:kaleyra/voice.git','git@bitbucket.org:kaleyra/whatsapp.git'
  deploymentJobs:
    - name: dev
      acl: [kaleyra*core-dev]
    - name: prod
      acl: [kaleyra*PROD]  
    - name: stage
      acl: [kaleyra*core-stage] 
    - name: preprod
      acl: [kaleyra*core-preprod]              
    - name: ci
      acl: [kaleyra*core-devops]      
       
  master:
    ingress:
      enabled: true
    resources:
      limits:
        cpu: "2000m"
        memory: "4096Mi"
    javaOpts: "-Xms2560M -Xmx2560M -Duser.timezone=Asia/Calcutta"

nginx-ingress:
  replicas: 1
  default-backend-service: "jenkins/jenkins"
  namespace: jenkins
  cert-issuer: "letsencrypt-staging"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "EECDH+CHACHA20:EECDH+AES"
  ssl-ecdh-curve: "X25519:prime256v1:secp521r1:secp384r1"
  controller:
    image:
      repository: gajentechm/nginx-ingress-controller
      tag: "0.26.1"

cert-manager:
  namespace: jenkins
  email: "coe-devops@kaleyra.com"

cluster-autoscaler:
  namespace: jenkins
  cloudProvider: aws  
  awsRegion: ap-south-1
  autoDiscovery:
    clusterName: cicd
    tags:
    - kubernetes.io/cluster/cicd

postgres:
  namespace: jenkins
  postgresDatabase: ci_database
