replicaCount: 1

appName: hexa-api

image:
  repository: 167578521290.dkr.ecr.ap-south-1.amazonaws.com/kcloud-ti
  tag: "hexa-apiv"
  sprint: 1

volumes:
  name: hexa-nfs
  mountPath: "/mnt/hexa-nfs"

service:
  type: nodePort
  port: 80
  nodePort: 30093
app:
  containerPort: 80