{{- with index .Values "cluster-configs" "secrets" "common" }}
{{- if index . "clientSecret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-credentials
  namespace: {{ .namespace }}
type: Opaque
data:
  db_username: {{ index . "db_username" | b64enc | quote }}
  db_password: {{ index . "db_password" | b64enc | quote }}
  rbac_service_api_key: {{ index . "rbac_service_api_key" | b64enc | quote }}
  redis_password: {{ index . "redis_password" | b64enc | quote }}
  stripe_publishable_key: {{ index . "stripe_publishable_key" | b64enc | quote }}
  razorpay_key: {{ index . "razorpay_key" | b64enc | quote }}
  freshsales_api_key: {{ index . "freshsales_api_key" | b64enc | quote }}
  app_salt_16byte: {{ index . "app_salt_16byte" | b64enc | quote }}
  encrypt_key: {{ index . "encrypt_key" | b64enc | quote }}
  encrypt_iv: {{ index . "encrypt_iv" | b64enc | quote }}
  record_aws_access_key_id: {{ index . "record_aws_access_key_id" | b64enc | quote }}
  record_aws_secret_access_key: {{ index . "record_aws_secret_access_key" | b64enc | quote }}
  aws_access_key_id: {{ index . "aws_access_key_id" | b64enc | quote }}
  aws_secret_access_key: {{ index . "aws_secret_access_key" | b64enc | quote }}
  global_db_username: {{ index . "global_db_username" | b64enc | quote }}
  global_db_password: {{ index . "global_db_password" | b64enc | quote }}
  public_rabbitmq_username: {{ index . "public_rabbitmq_username" | b64enc | quote }}
  public_rabbitmq_password: {{ index . "public_rabbitmq_password" | b64enc | quote }}
  rabbitmq_username: {{ index . "rabbitmq_username" | b64enc | quote }}
  rabbitmq_password: {{ index . "rabbitmq_password" | b64enc | quote }}
  app_key: {{ index . "app_key" | b64enc | quote }}
{{- end }}
{{- end }}