{{- with index .Values "cluster-configs" "secrets" "jenkins" }}
{{- if index . "clientSecret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-credentials
  namespace: {{ .namespace }}
type: Opaque
data:
  clientID: {{ index . "clientId" | b64enc | quote }}
  clientSecret: {{ index . "clientSecret" | b64enc | quote }}
  gitReadAccessToken: {{ index . "gitReadAccessToken" | b64enc | quote }}
  gitReadSshPrivateKey: {{ index . "gitReadSshPrivateKey" | b64enc | quote }}
  ecrConfigJson: {{ index . "ecrConfigJson" | b64enc | quote }}
  dockerConfigJson: {{ index . "dockerConfigJson" | b64enc | quote }}
  slackToken: {{ index . "slackToken" | b64enc | quote }}
  dockerUserName: {{ index . "dockerUsername" | b64enc | quote }}
  dockerPassword: {{ index . "dockerPassword" | b64enc | quote }}
  ciDbUsername: {{ index . "ciDbUsername" | b64enc | quote }}
  ciDbpassword: {{ index . "ciDbpassword" | b64enc | quote }}
  aws_ecr_access_key_id: {{ index . "aws_ecr_access_key_id" | b64enc | quote }}
  aws_ecr_secret_access_key: {{ index . "aws_ecr_secret_access_key" | b64enc | quote }}
{{- end }}
{{- end }}