apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiApp.appName }}
  namespace: {{ .Values.apiApp.namespace }}
spec:
  replicas: {{ .Values.apiApp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.apiApp.appName }}
      
  template:
    metadata:
      labels:
        app: {{ .Values.apiApp.appName }}
    spec:
      volumes:
        - name: {{ .Values.commonVolume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.commonVolume.name }} 

      containers:
        - name: {{ .Values.apiApp.appName }}
          image: "{{ .Values.commonECR.repository }}:{{ .Values.apiApp.image.tag }}{{ .Values.apiApp.image.sprint }}"
          ports:
            containerPort: {{ .Values.apiApp.port.containerPort }}