{{- define "common.deployment" -}}
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ template "common.name" . }}
  namespace: {{ .Values.namespace }}
spec:
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
  selector:
    matchLabels:
      app: {{ .Values.appName  . | nindent 6 }}   
{{- end }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:  
      labels:
        app: {{ .Values.appName  . | nindent 8 }}            
    spec:
    {{- if .Values.pvc.mountHexaNFS "true" }}
      volumes:  
      - name: hexa-nfs
        peristentVolumeClaim:
          claimName: hexa-nfs
    {{- end }}
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.accountID }}.dkr.ecr.{{ .Values.image.region }}.amazonaws.com/{{ .Values.image.repoName }}:{{ .Values.image.tags }}v{{ .Values.image.sprint }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}  
          ports:
            - containerPort: {{ .Values.httpPort }}
              
      {{- if .Values.healthChecks.enabled }}              
          readinessProbe:
          {{- tpl  .Values.healthChecks.readinessProbe . | nindent 12 }} 
          livenessProbe:
          {{- tpl  .Values.healthChecks.livenessProbe . | nindent 12 }}                      
       {{- end }}       
        {{- if .Values.lifecycle }}
          lifecycle:
          {{- toYaml .Values.lifecycle | nindent 12 }}
        {{- end }}      
        {{- if or .Values.initContainers.gitSync.enabled .Values.extraVolumeMounts }}
          volumeMounts:
        {{- if -eq .Values.mountHexaNFS "true"}}
          - name: hexa-nfs
            mountPath: "/mnt/hexa-nfs/"
        {{- end}}
          env:  
        {{- if .Values.env }}                                   
          {{- tpl  .Values.env . | nindent 12 }}
        {{- end -}}         
      {{- end }}
      {{- if .Values.resources }}                                     
          resources:
            {{- tpl .Values.resources . | nindent 12 }}
      {{- end }}            
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
