# Hexa-API
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiApp.appName }}
spec:
  type: {{ .Values.apiApp.service.type }}
  selector:
    app: {{ .Values.apiApp.appName }}
  ports:
    - port: {{ .Values.apiApp.service.port }}
      nodePort: {{ .Values.apiApp.service.nodePort }}
# Hexa-API 
---

