# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/dev\-secrets\.yaml$
          #kms: 
          #gcp_kms: 
          #pgp:    

        - path_regex: environments/stag\-secrets\.yaml$
          #kms: 
          ##gcp_kms: 
          #pgp:   

        - path_regex: environments/uat\-secrets\.yaml$
          #kms: arn:aws:kms:ap-south-1:167578521290:key/bb6bb418-6c1c-42c4-a2aa-dd2816eea300
          ##gcp_kms: 
          #pgp:    
       
        - path_regex: environments/staging\-secrets\.yaml$
          #kms: 
          ##gcp_kms: 
          #pgp:   

        # CI ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/ci\-secrets\.yaml$ 
          encrypted_regex: '^(secrets)$'
          pgp: '39E63430006C6B4EAD11CC9BC52376224230FED9'
          kms: arn:aws:kms:ap-south-1:167578521290:key/bb6bb418-6c1c-42c4-a2aa-dd2816eea300                

