cluster-configs:
  db:
    namespace: kaleyra
    name: db-service
    port: 5432
    targetPort: 5432

  root-ingress:
    name: root-ingress
    namespace: kaleyra
    cert-issuer: "letsencrypt-staging"
    appRoot: citizen
    serviceName: citizen
    servicePort: 80
 
  nginx-errors:
    enabled: false
    name: nginx-errors
    namespace: kaleyra
    serviceName: nginx-errors
    servicePort: 80

  configmaps:
    kaleyra-config:
      namespace: [ kaleyra , monitoring]
      name: kaleyra-config
      server-tomcat-max-connections: "500"
      server-tomcat-max-threads: "10"
      spring-datasource-tomcat-initialSize: "1"
      spring-datasource-tomcat-max-active: "2"
      spring-jpa-show-sql: "true"  

    kaleyra-service-host:    
      name: kaleyra-service-host
      namespace: [ kaleyra, monitoring ] 

  secrets:
    alertmanager:
      namespace: monitoring
      name: alertmanager-main      

    jenkins:
      namespace: jenkins
      name: jenkins 
