# Common Labels
labels:
  app: "api-service"
  group: "cap"

# Ingress Configs
ingress:
  enabled: true
  context: "api-service"
  ip-whitelist: "0.0.0.0/0"
  additionalAnnotations: | 
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ index .Values "ingress" "ip-whitelist" | quote }}

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "api-service-db"
    image:
      repository: "api-service-db"

# Container Configs
image:
  repository: "api-service:master"
replicas: "1"
appType: "java-spring"
app_log_level: info
log_level: false
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |  
  - name: CORE_CONFIG
    valueFrom:
      configMapKeyRef:
        name: core-config
        key: core-something
  - name: FRESHSALES_API_KEY
    valueFrom:
      secretKeyRef:
        name: core-config
        key: core-something   

  - name: APP_LOG_FILESIZE
    value: {{ index .Values "app_log_filesize" | quote }}
  {{- if index .Values "app_env" | quote }}
  - name: FROM_EMAIL
    value: {{ index .Values "qa_from_email" | quote }}
  {{- end }}
