# Common Labels
labels:
  app: "api-service"
  group: "cap"

# Container Configs
image:
  repository: "api-service"
  tag: "master"
replicas: "1"
app_log_level: info
log_level: false

# Additional Container Envs
env: |  
  - name: APP_NAME
    value: {{ index .Values "app_name" | quote }}
  - name: APP_ENV
    value: {{ index .Values "app_env" | quote }}
  - name: APP_KEY
    value: {{ index .Values "app_key" | quote }}
  - name: APP_DEBUG
    value: {{ index .Values "app_debug" | quote }}
  - name: APP_URL
    value: {{ index .Values "app_url" | quote }}
  - name: APP_TIMEZONE
    value: {{ index .Values "app_timezone" | quote }}
  - name: LOG_CHANNEL
    value: {{ index .Values "log_channel" | quote }}
  - name: LOG_SLACK_WEBHOOK_URL
    value: {{ index .Values "log_slack_webhook_url" | quote }}
  - name: CACHE_DRIVER
    value: {{ index .Values "cache_driver" | quote }}
  - name: QUEUE_CONNECTION
    value: {{ index .Values "queue_connection" | quote }}
  - name: TRACE_LOG_PATH
    value: {{ index .Values "trace_log_path" | quote }}
  - name: APP_LOG_FILESIZE
    value: {{ index .Values "app_log_filesize" | quote }}
  - name: APP_LOG_LEVEL
    value: {{ index .Values "app_log_level" | quote }}
 