{{- with index .Values "cluster-configs" "rbac" }}
{{- range $idx, $v := . }}
{{- range $nsidx, $nsval := .namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaleyra-{{ $v.role }}
  namespace: {{ $nsval }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kaleyra-{{ $v.role }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kaleyra-user        
---
{{- end }}
{{- end }}
{{- end }}