# Default values for commons.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
global:
    containerRegistry: 167578521290.dkr.ecr.ap-south-1.amazonaws.com/kcloud

namespace: kaleyra
replicas: 1
httpPort: 8080
appType: ""
         
image:
  accountID: 761525537899   
  region: ap-south-1
  repoName: kcloud-stage
  tags: alpine-node14 
  pullPolicy: IfNotPresent
  sprint: 1.0.0   

 
# 761525537899.dkr.ecr.ap-south-1.amazonaws.com/hexarepo:alpine-node14-nginx

affinity:
    preferSpreadAcrossAZ: true

## Add additional volumes and mounts, e. g. for custom themes
extraVolumes: 
extraVolumeMounts: 

service:
  serviceName: nginx
  servicePort: 80
  serviceNodePort: 30001
  
pvc:
  mountHexaNFS: false
  mountPath: /mnt/hexa-nfs/