# Default values for commons.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
global:
    containerRegistry: 167578521290.dkr.ecr.ap-south-1.amazonaws.com

namespace: kaleyra
httpPort: 8080
appType: "micro"
         
image:
  accountID: 167578521290   
  region: ap-south-1
  repoName: kcloud
  tags: alpine-node14 
  pullPolicy: IfNotPresent
  sprint: 1.0.0   

 
# 761525537899.dkr.ecr.ap-south-1.amazonaws.com/hexarepo:alpine-node14-nginx

affinity:
    preferSpreadAcrossAZ: true

service:
  serviceName: nginx
  servicePort: 80
  serviceNodePort: 30001
  
extraVolumeMounts: |
  - mountPath: /mnt/hexa-nfs/
    name: hexa-nfs

extraContainers: |

env: |

# Additional Container Envs
extraEnv: 
  shared: |  
      - name: LOOKUP_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: lookup_url
      - name: KSMS_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: ksms_url
      - name: RBAC_SERVICE_API_KEY
        valueFrom:
          secretKeyRef: 
            name: common
            key: rbac_service_api_key
      - name: FILE_VALIDATION_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: file_validation_url
      - name: BILLINGS_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: billings_url
      - name: BILLINGS_DOMAIN
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: billings_domain
      - name: RAZORPAY_KEY
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: razorpay_key
      - name: STRIPE_PUBLISHABLE_KEY
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: stripe_publishable_key
      - name: PAYMENT_CALLBACK_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: payment_callback_url
      - name: DEMO_CREDIT_EMAIL_NOTIFICATION
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: demo_credit_email_notification
      - name: CONTACTS_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: contacts_url
      - name: VECTOR_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: vector_url
      - name: CAMPAIGN_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: campaign_url
      - name: REPORTS_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: reports_url
      - name: INSIGHTS_OVERVIEW_MAILER_LIST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: insights_overview_mailer_list
      - name: WHATSAPP_NFS_PATH_WITH_SLASH
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: whatsapp_nfs_path_with_slash
      - name: WHATSAPP_MOUNT_PATH
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: whatsapp_mount_path
      - name: WHATSAPP_SANDBOX_NUMBER
        valueFrom:
          secretKeyRef: 
            name: common
            key: whatsapp_sandbox_number
      - name: WHATSAPP_SERVICE_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: whatsapp_service_url
      - name: WHATSAPP_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: whatsapp_url
      - name: WHATSAPP_SUBSCRIPTION_PRICE
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: whatsapp_subscription_price
      - name: FROM_EMAIL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: from_email
      - name: EMAIL_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: email_url
      - name: ADMIN_EMAIL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: admin_email
      - name: ADMIN_NAME
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: admin_name
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef: 
            name: common
            key: aws_access_key_id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef: 
            name: common
            key: aws_secret_access_key
      - name: AWS_BUCKET
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: aws_bucket
      - name: AWS_DEFAULT_REGION
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: aws_default_region
      - name: RBAC_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: rbac_url
      - name: SURFACE_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: surface_url
      - name: CATALOGUE_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: catalogue_url
      - name: VERIFY_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: verify_url
      - name: FRESHSALES_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: freshsales_url
      - name: FRESHSALES_API_KEY
        valueFrom:
          secretKeyRef: 
            name: common
            key: freshsales_api_key
      - name: CRM_ENABLE_ENV
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: crm_enable_env
      - name: APP_SALT_16BYTE
        valueFrom:
          secretKeyRef: 
            name: common
            key: app_salt_16byte
      - name: INTERNAL_LOG_TIME_TRACK
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: internal_log_time_track
      - name: AWS_BUCKET_PRIVATE
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: aws_bucket_private
      - name: TXTLY_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: txtly_url
      - name: SG_HOST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: sg_host
      - name: DEFAULT_POD
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: default_pod
      - name: CURRENT_POD
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: current_pod
      - name: LOGIN_COOKIE_DOMAIN
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: login_cookie_domain
      - name: EU_HOST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: eu_host
      - name: RECORDING_ACCESS_LIMIT
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: recording_access_limit
      - name: RECORD_AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef: 
            name: common
            key: record_aws_access_key_id
      - name: RECORD_AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef: 
            name: common
            key: record_aws_secret_access_key
      - name: RECORD_AWS_BUCKET
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: record_aws_bucket
      - name: RECORD_AWS_DEFAULT_REGION
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: record_aws_default_region
      - name: ENCRYPT_KEY
        valueFrom:
          secretKeyRef: 
            name: common
            key: encrypt_key
      - name: ENCRYPT_IV
        valueFrom:
          secretKeyRef: 
            name: common
            key: encrypt_iv
      - name: APPROVALS_QUEUE
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: approvals_queue
      - name: EXCLUDE_THROTTLING_IP
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: exclude_throttling_ip
      - name: HOST_SUPPORTED
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: host_supported
      - name: SG_NAME
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: sg_name
      - name: EU_NAME
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: eu_name
      - name: IN_NAME
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: in_name
      - name: ACTIVITY_LOG_QUEUE
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: activity_log_queue
      - name: KFLOW_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: kflow_url
      - name: KALEYRA_GLOBAL_CALLBACK_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: kaleyra_global_callback_url
      - name: CALLBACK_URL
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: callback_url
      - name: SCHEDULE_MIN_LIMIT
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: schedule_min_limit
      - name: RBAC_URL
        valueFrom:
          configMapKeyRef:
            name: kaleyra-service-host
            key: rbac_url
      - name: DB_CONNECTION
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: db_connection
      - name: GLOBAL_DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: common
            key: global_db_username
      - name: GLOBAL_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: common
            key: global_db_password    
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: common
            key: db_username 
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: common
            key: db_password
      - name: PUBLIC_RABBITMQ_USERNAME
        valueFrom:
          secretKeyRef:
            name: common
            key:  public_rabbitmq_username
      - name: PUBLIC_RABBITMQ_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: common
            key: public_rabbitmq_password
      - name: RABBITMQ_USERNAME
        valueFrom: 
          secretKeyRef:
            name: common
            key: rabbitmq_username
      - name: RABBITMQ_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: common
            key: rabbitmq_password
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: common
            key: redis_password
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: db_host
      - name: DB_PORT
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: db_port
      - name: DB_DATABASE
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: db_database
      - name: GLOBAL_DB_HOST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: global_db_host
      - name: GLOBAL_DB_PORT
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: global_db_port
      - name: GLOBAL_DB_DATABASE
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: global_db_database
      - name: RABBITMQ_HOST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: rabbitmq_host
      - name: RABBITMQ_PORT
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: rabbitmq_port
      - name: PUBLIC_RABBITMQ_HOST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: public_rabbitmq_host
      - name: PUBLIC_RABBITMQ_PORT
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: public_rabbitmq_port
      - name: REDIS_HOST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: redis_host
      - name: REDIS_PORT
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: redis_port
      - name: REDIS_VOICE_PORT
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: redis_voice_port
      - name: REDIS_VOICE_HOST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: redis_voice_host
      - name: REDIS_SMS_HOST
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: redis_sms_host
      - name: REDIS_SMS_PORT
        valueFrom:
          configMapKeyRef:
            name: core-config
            key: redis_sms_port


