# Default values for commons.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
global:
    containerRegistry: <> #should be ecr

namespace: kaleyra
replicas: 1
httpPort: 8080
appType: ""

####### HEXA-API ########
apiApp:
  namespace: cap #Common-Application
  replicaCount: 1
  appName: hexa-api
  image:
    tag: "hexa-apiv"
    sprint: 1
  service:
    type: nodePort
    port: 80
    nodePort: 30093
  port:
    containerPort: 80
  
#### HEXA-API #################
# This is for Hexa-NFS volume
commonVolume:
  name: hexa-nfs
  mountPath: "/mnt/hexa-nfs"
### HEXA-NFS ##################
## ECR ##
commonECR:
  repository: 167578521290.dkr.ecr.ap-south-1.amazonaws.com/kcloud-ti
## ECR ##


image:
  pullPolicy: IfNotPresent   

affinity:
    preferSpreadAcrossAZ: true



  gitSync:
    enabled: false
    image:
      repository: k8s.gcr.io/git-sync
      tag: v3.1.1
      pullPolicy: IfNotPresent   
    env: |
        - name: "GIT_SYNC_REPO"
          value: "{{ .Values.initContainers.gitSync.repo }}"
        - name: "GIT_SYNC_BRANCH"
          value: "{{ .Values.initContainers.gitSync.branch }}"        
        - name: "GIT_SYNC_DEPTH"
          value: "1"            
        - name: "GIT_SYNC_ONE_TIME"
          value: "true"          
        - name: "GIT_SYNC_SSH"
          value: "true"      
        - name: "GIT_SYNC_ROOT"
          value: "/work-dir"

healthChecks:
    enabled: false
    livenessProbe: |
        httpGet:
            path: "{{ .Values.healthChecks.livenessProbePath }}"
            port: {{ .Values.httpPort }}
        initialDelaySeconds: 30
        timeoutSeconds: 3
        periodSeconds: 60
        successThreshold: 1
        failureThreshold: 5
    readinessProbe: |
        httpGet:
            path: "{{ .Values.healthChecks.readinessProbePath }}"
            port: {{ .Values.httpPort }}
        initialDelaySeconds: 30
        timeoutSeconds: 3
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 5        

lifecycle:
    preStop:
        exec:
            command:
            - sh
            - -c
            - "sleep 10"

memory_limits: "512Mi"
resources: |
  {{- if eq .Values.appType "java-spring" -}}
  requests:
    memory: {{ .Values.memory_limits | quote }}
  limits:
    memory: {{ .Values.memory_limits | quote }}
  {{- end -}}
## Allows specification of additional environment variables
extraEnv:
  
## Additional init containers
extraInitContainers: |

## Additional sidecar containers
extraContainers: |

## Add additional volumes and mounts, e. g. for custom themes
extraVolumes: |
extraVolumeMounts: |

additionalLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000            

service:
  additionalAnnotations: {}

serviceMonitor:
  honorLabels: true
  # interval: 2m  

cron:
  namespace: kaleyra
  concurrencyPolicy: Forbid
  restartPolicy: OnFailure
  httpPort: 8080
  ## Additional sidecar containers
  extraContainers: |

  ## Add additional volumes and mounts
  extraVolumes: |

  ## Add additional mounts
  extraVolumeMounts: |

vpa:
  enabled: false  
  updateMode: "Off"
