# Common Labels
labels:
  app: "bills"
  group: "core"


# Container Configs
image:
  repository: "bills"
  tag: "2.0"
replicas: 1
app_log_level: info
log_level: false

extraVolumeMounts: |
  - mountPath: /mnt/hexa-nfs/
    name: hexa-nfs

# Additional Container Envs